version: "3"
services:
  api:
    image: koraykural/ituprogram-api
    ports:
      - "3000:3000"
    networks:
      - nginx-routing
    env_file: .env
  update-service:
    image: koraykural/ituprogram-update-service
    env_file: .env
  client-main:
    image: koraykural/ituprogram-client-main
    ports:
      - "4200:4200"
    networks:
      - nginx-routing
  client-archive:
    image: koraykural/ituprogram-client-archive
    ports:
      - "4201:4201"
    networks:
      - nginx-routing
  nginx:
    image: koraykural/ituprogram-nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
      - client-main
      - client-archive
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    restart: always
    networks:
      - nginx-routing
networks:
  nginx-routing:
    driver: bridge
