version: "3"
services:
  api:
    image: koraykural/ituprogram-api
    networks:
      - nginx-routing
    env_file: .env
    restart: on-failure
  update-service:
    image: koraykural/ituprogram-update-service
    env_file: .env
    restart: on-failure
  client-main:
    image: koraykural/ituprogram-client-main
    networks:
      - nginx-routing
  client-new:
    image: koraykural/ituprogram-client-new
    networks:
      - nginx-routing
  client-archive:
    image: koraykural/ituprogram-client-archive
    networks:
      - nginx-routing
  nginx:
    image: koraykural/ituprogram-nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
      - client-main
      - client-archive
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    restart: always
    networks:
      - nginx-routing
networks:
  nginx-routing:
    driver: bridge
