FROM node:12-alpine
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY package.json /usr/src/app/
RUN npm install -g nodemon
RUN npm install
EXPOSE 3000
COPY . /usr/src/app
CMD ["npm", "run", "dev"]
